# Generated by Django 4.0.1 on 2022-01-06 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(default='', verbose_name='Blog Comment'),
        ),
    ]
