# Generated by Django 4.0.1 on 2022-01-10 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0004_blog_sub_title_alter_blog_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-published']},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-commented',)},
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='', upload_to='blogs', verbose_name='Image'),
        ),
    ]
