# Generated by Django 4.0.1 on 2022-01-06 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(default=0, verbose_name='Bio'),
            preserve_default=False,
        ),
    ]
