# Generated by Django 4.0.1 on 2022-01-07 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_login', '0002_userprofile_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='joined',
        ),
    ]
